"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup


setup(
    name='Bauchan',
    app=['bauchand.py'],
    data_files=[],
    options=dict(
        py2app=dict(
            plist=dict(
                Label='org.example.bauchan',
                LSUIElement=True,
                RunAtLoad=True,
                LaunchOnlyOnce=True,
                ProgramArguments=['Contents/MacOS/Bauchan'],
                Disabled=False,
                ProcessType='Interactive',
            ),
            resources=[
                'bauchan.py',
                'common.py',
                'org.example.bauchan.agent.plist',
            ]
        )
    ),
    setup_requires=[
        'py2app',
    ],
    install_requires=[
        'rumps',
    ],
)
